### ISSUE TITLE
Special case "CSQ", "Restricted", and other non-tone values from Repeaterbook

### ISSUE THREAD

**Issue by masenf** [mycodeplug/dzcb#41]
A regression introduced in 0.2.0 with the new repeaterbook API ingest:

Before:
https://github.com/mycodeplug/dzcb/blob/d9fe8fe00903e807c119a11aa87f5268c3e06ce0/src/dzcb/repeaterbook.py#L141-L142

Now:
https://github.com/mycodeplug/dzcb/blob/6377bd1d9fbf7682bf6a8bb34fd31a847e280e4b/src/dzcb/repeaterbook.py#L167-L168

Note how the "CSQ" special case is removed. Apparently there are _other_ values that this field can take on (`restricted`), so dzcb probably needs a "tone normalizer" to detect valid values and log/ignore any channels with invalid tones. A naive approach would be to check for `tone.startswith("D") or float(tone)`. A better approach would be to check against a table of well-known tones.

**Comment by hillsboro** [comment]
thanks for the fix!  Agree with not generating channels that contain invalid tone fields returned from repeaterbook.
