### ISSUE TITLE
dzcb generates incorrect ColorCode in editcp output

### ISSUE THREAD

**Issue by jschiefer** [mycodeplug/dzcb#84]
dzcb often creates two conflicting fields for the ColorCode of a channel, in cases where the color code is not 1. You can observe this as follows: 
* Retrieve the [latest codeplug from mycodeplug/example-codeplug](https://github.com/mycodeplug/example-codeplug/actions/runs/1770887941)
* Import the file default/example-md-uv380.jscon into editcp (tested with 1.0.29). Ignore warning about invalid channel names.
* Find the channel named "WA 1 SCE". Observe that the Color Code field in the UI is incorrectly  set to 1.
* Open the file example-md-uv380.json with an editor. Line 115509, is the beginning of the channel definition for "WA 1 SCE"
* Line 115513 contains the following definition: `"ColorCode": "On"`
* Line 115559 contains the definition `"Color Code": "2"`.
* Editing the Json file by hand, removing the first definition and changing the second one to `"ColorCode": "2"` results in a correct import for this channel.
* I noticed that the `ColorCode` definition is present for all channels, whereas the `Color Code` one is not.

**Comment by masenf** [comment]
Confirmed issue. Excellent bug report, this has been a day zero bug.

**Comment by masenf** [comment]
@jschiefer please try again with the new release 0.3.7 and thanks again for reporting this issue

regenerated the example with 0.3.7 here: https://github.com/mycodeplug/example-codeplug/releases/tag/2022-03-26

**Comment by jschiefer** [comment]
I did verify this with [my own codeplug](https://github.com/jschiefer/ac7td-codeplug), and did some spot checks - the problem is fixed. Also, editcp no longer complains about invalid records - nice!

Thank you for the super-quick turn-around, and for writing this software to begin with - very useful and well thought out!

**Comment by masenf** [comment]
> Also, editcp no longer complains about invalid records - nice!

Ah yes, that was a partial bonus fix for #75 that I noticed while testing the main fix.

Glad to hear it’s working for you, and thanks for digging in and using the code. Definitely send over any other bugs or general ideas for improvement you might have.
